<?php

namespace App\Http\Controllers;

use App\Models\Publication;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class AddPublicationController extends Controller
{
    public function create()
    {
        return view('operator.AddPublication');
    }
    
    public function store(Request $request)
    {
        // Validate input
        $request->validate([
            'title' => 'required|string|max:255',
            'author' => 'required|string|max:255',
            'date' => 'required|date',
            'contents' => 'required|string',
            'file' => 'required|mimes:pdf|max:10000',
        ]);

        // Store PDF file
        $storedPath = $request->file('file')->store('publications', 'public');
        $fileUrl = str_replace('public/', 'storage/', $storedPath);

        // Create publication (UUID auto-generated by model)
        Publication::create([
            'title'       => $request->title,
            'author'      => $request->author,
            'date'        => $request->date,
            'abstract'    => $request->contents,
            'file_url'    => $fileUrl,
            'status'      => 'requested',
            'created_by'  => Auth::id(),
            'note_admin'  => null,
            'approved_by' => null,
            'rejected_by' => null,
        ]);

        return redirect()
            ->route('operator.approval_status')
            ->with('success', 'Publication submitted! Waiting for admin approval.');
    }
}

